MentorCity V.1.1.0
PinkMoon25/Book_an_appointment_API pull request #22
Opened 2022-12-08 16:43 UTC by Lizdev-05

# Hi there 👋🏻

**Thanks for taking the time to review the project. Here are some things important to note about it:**

## Frontend Link

**You can find the link for the frontend project https://github.com/PinkMoon25/Book_an_appointment_front_end/pull/9**

## Now into the project...

**This project was done following git-flow, for which we have different pull requests, each of them with specific information about each feature. You can refer to them below**

- ✅ https://github.com/PinkMoon25/Book_an_appointment_API/pull/14. Here was the basic project configuration.
- ✅ https://github.com/PinkMoon25/Book_an_appointment_API/pull/15. Here we serialized the JSON response for users
- ✅ https://github.com/PinkMoon25/Book_an_appointment_API/pull/16. We set up model controllers and associations 
- ✅ https://github.com/PinkMoon25/Book_an_appointment_API/pull/17. We set up API for the home page 
- ✅ https://github.com/PinkMoon25/Book_an_appointment_API/pull/18. We added an endpoint for reservation
- ✅ https://github.com/PinkMoon25/Book_an_appointment_API/pull/19. We added test
- ✅ https://github.com/PinkMoon25/Book_an_appointment_API/pull/20. We added the documentation
- ✅ The project follows the style guidelines
- ✅ The project was developed following the TDD approach. Thus, almost every feature is tested

# Final notes 📔

_Is expected that this project meets the requirements. Please let me know if anything is left to be done or can be improved. Again, thanks for the review._

2022-12-08 18:33 UTC, Meltrust requested changes
Hi @Lizdev-05,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  APIis is working well✔️ 
-  Good readme ✔️ 




#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._

_I strongly recommend you take them into account as they can improve your final evaluation._





Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2022-12-08 18:33 UTC, Meltrust commented on db/migrate/20221206175744_add_subject_to_reservations.rb
> +end
- [ ] For a new user, it is impossible to run the migrations.  That is why it is never recommended to edit the migrations after they are already done:

![image](https://user-images.githubusercontent.com/57421823/206524071-7ae79c3b-737b-4510-9319-baaafda78c7c.png)

## Explanation

Your project runs well on your machine because the migrations have been already implemented.  Even if the migration files have any new errors, your database is untouched.  

For a new user who needs to apply the migrations for the first time, this is a whole different story.  They will fail.

Remember that the final evaluator needs to be able to run the project without any hassle.

## Tips and Extra help

Run this command:  `rake db:migrate VERSION=0`.  This will undo all the migrations.  After that, you can apply one by one and skip the problematic one.  The error message should give you a good idea of what is the problem.

Then, reseed the database and it will be fixed .  💪

2022-12-08 18:33 UTC, Meltrust commented on README.md
> +```
- [ ] When I run your tests according to your instructions, I get this:

![image](https://user-images.githubusercontent.com/57421823/206526465-30b9ad1d-4489-4bdd-b095-d2f1bc6066ee.png)

If your tests should not be run like that, kindly change the instructions.  If one or more of your tests are failing, kindly fix them to ensure the integrity of your app.

2022-12-08 18:33 UTC, Meltrust commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ]  On the "License" section of your readme, the link is broken because it points to a file that does not exist in your project.

## Tips and extra help

Go [here](https://github.com/microverseinc/readme-template), grab the `MIT.md` file from that repo, paste it on the root of your project, and link to it in the "License" section of your readme.

That way, your app will be well documented 💪

2022-12-08 21:02 UTC, PinkMoon25 commented on db/migrate/20221206175744_add_subject_to_reservations.rb
> +end
Hi @Meltrust , I have followed the above steps and redid the migrations :pray:

2022-12-08 21:03 UTC, PinkMoon25 commented on README.md
> +```
hi @Meltrust , I have added the correct steps to run tests

2022-12-08 21:03 UTC, PinkMoon25 commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
Done :+1:

2022-12-08 21:33 UTC, Meltrust commented
#### Hi @Lizdev-05,


# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)

### To highlight

- Migrations now work!✔️ 
- Readme has been corrected✔️ 
- API is working well✔️ 



Cheers and Happy coding!👏👏👏


------

2022-12-09 09:13 UTC, merged

2022-12-09 10:30 UTC, PinkMoon25 commented
tHANK YOU @Meltrust  :pray: